In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.decomposition import PCA
from random import *
from skrebate import ReliefF
# pip install skrebate
s = 'https://archive.ics.uci.edu/ml/'\
'machine-learning-databases/wine/wine.data'
#'machine-learning-databases/iris/iris.data'
print('From URL:', s)
df = pd.read_csv(s, header=None)
df.columns = ['Class label', 'Alcohol',
					'Malic acid', 'Ash',
					'Alcalinity of ash', 'Magnesium',
					'Total phenols', 'Flavanoids',
					'Nonflavanoid phenols',
					'Proanthocyanins',
					'Color intensity', 'Hue',
					'OD280/OD315 of diluted wines',
					'Proline']
print(df.info())
X = df.iloc[:,1:].values
L = df.iloc[:,0].values
r = ReliefF(n_neighbors=2, n_features_to_select=None)
M = r.fit(X, L)
for feature_name, feature_score in zip(df.drop('Class label', axis=1).columns,
                                       r.feature_importances_):
    print(feature_name, '\t', feature_score)
    
print(r.feature_importances_)

From URL: https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Class label                   178 non-null    int64
 1   Alcohol                       178 non-null    float64
 2   Malic acid                    178 non-null    float64
 3   Ash                           178 non-null    float64
 4   Alcalinity of ash             178 non-null    float64
 5   Magnesium                     178 non-null    int64
 6   Total phenols                 178 non-null    float64
 7   Flavanoids                    178 non-null    float64
 8   Nonflavanoid phenols          178 non-null    float64
 9   Proanthocyanins               178 non-null    float64
 10  Color intensity               178 non-null    float64
 11  Hue                           178 non-null    float64
 12  OD280/OD315 of diluted wines  178 non-null    float64
 13  Proline                       178 non-null    int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB
None
Alcohol 	 0.09716513897102308
Malic acid 	 0.029558222676200212
Ash 	 0.03318211860842393
Alcalinity of ash 	 0.05536893316344261
Magnesium 	 0.05821018563751833
Total phenols 	 0.13039519566059665
Flavanoids 	 0.18957414782155227
Nonflavanoid phenols 	 0.08943714225143104
Proanthocyanins 	 0.09312196505157196
Color intensity 	 0.10246337720980175
Hue 	 0.09616789988124597
OD280/OD315 of diluted wines 	 0.19254434703872908
Proline 	 0.15406962765872192
[0.09716514 0.02955822 0.03318212 0.05536893 0.05821019 0.1303952
 0.18957415 0.08943714 0.09312197 0.10246338 0.0961679  0.19254435
 0.15406963]

In [6]:
X = df.iloc[:,1:]
L = df.iloc[:,0]

In [9]:
df.iloc[:,1:]

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [8]:
df.iloc[:,0]

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Class label, Length: 178, dtype: int64