In [14]:
import pickle
import os

# Función para desempaquetar los archivos
def unpickle(file):
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

# Ruta de la carpeta que contiene los archivos de datos
data_dir = r'.\cifar-10-batches-py'

# Lista para almacenar los datos
data = []

# Cargar cada archivo en la carpeta
for filename in os.listdir(data_dir):
    if filename.startswith('data_batch'):
        file_path = os.path.join(data_dir, filename)
        print(file_path)  # Imprime la ruta completa del archivo
        data_dict = unpickle(file_path)
        data.extend(data_dict[b'data'])

# Ahora 'data' es una lista con todas las imágenes del conjunto de datos
print(f'Número total de imágenes: {len(data)}')

.\cifar-10-batches-py\data_batch_1
.\cifar-10-batches-py\data_batch_2
.\cifar-10-batches-py\data_batch_3
.\cifar-10-batches-py\data_batch_4
.\cifar-10-batches-py\data_batch_5
Número total de imágenes: 50000

In [18]:
import numpy as np
import pandas as pd

# Convertir la lista en un array de numpy
data_array = np.array(data)

# Convertir el array en un DataFrame de pandas
df = pd.DataFrame(data_array)

df

,0,1,2,3,4,5,6,7,8,9,...,3062,3063,3064,3065,3066,3067,3068,3069,3070,3071
0,59,43,50,68,98,119,139,145,149,149,...,59,58,65,59,46,57,104,140,84,72
1,154,126,105,102,125,155,172,180,142,111,...,22,42,67,101,122,133,136,139,142,144
2,255,253,253,253,253,253,253,253,253,253,...,78,83,80,69,66,72,79,83,83,84
3,28,37,38,42,44,40,40,24,32,43,...,53,39,59,42,44,48,38,28,37,46
4,170,168,177,183,181,177,181,184,189,189,...,92,88,85,82,83,79,78,82,78,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,145,151,156,155,153,153,157,161,161,161,...,72,68,64,61,63,59,57,56,53,54
49996,255,254,255,254,254,254,254,253,254,254,...,57,61,64,68,64,76,82,79,81,76
49997,35,40,42,39,43,45,48,51,53,56,...,91,94,104,103,96,93,87,77,66,50
49998,189,186,185,184,182,181,180,180,181,180,...,160,166,171,171,172,169,165,169,171,171
49999,229,236,234,231,236,242,246,246,242,236,...,136,141,147,158,168,171,174,173,162,161

In [19]:
# Informacion del DataFrame
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Columns: 3072 entries, 0 to 3071
dtypes: uint8(3072)
memory usage: 146.5 MB
None

In [20]:
# Verificar si hay valores faltantes en todo el DataFrame
hay_nans = df.isnull().values.any()
print(hay_nans)

False